In [1]:
ls

 磁碟區 C 中的磁碟是 Windows
 磁碟區序號:  A631-A59D

 C:\Users\user\dm\TKU-DM-611630392 的目錄

2022/09/29  上午 10:21    <DIR>          .
2022/09/28  下午 11:50    <DIR>          ..
2022/09/29  上午 10:21    <DIR>          .ipynb_checkpoints
2022/09/29  上午 01:03            34,641 0922.ipynb
2022/09/29  上午 10:21                72 0929.ipynb
2022/09/28  下午 11:50                28 README.md
2022/09/29  上午 01:01           151,247 scores.csv
2022/09/28  下午 11:50             1,423 Untitled2.ipynb
2022/09/28  下午 11:50             5,459 上課內容.ipynb
               6 個檔案         192,870 位元組
               3 個目錄  920,200,646,656 位元組可用


In [9]:
%%writefile hi.py
print("hi 929")
#新增檔案使用

Overwriting hi.py


In [8]:
run hi.py

hi 929


In [10]:
a=1

In [11]:
b=2

In [33]:
whos
#確認變數有那些東西 要記起來

Variable   Type       Data/Info
-------------------------------
a          int        1
b          int        2
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
np1        ndarray    4: 4 elems, type `int32`, 16 bytes
np2        ndarray    4: 4 elems, type `int32`, 16 bytes
np3        ndarray    16: 16 elems, type `int32`, 64 bytes
np4        ndarray    10: 10 elems, type `float64`, 80 bytes
np5        ndarray    5: 5 elems, type `float64`, 40 bytes
np6        ndarray    5x2: 10 elems, type `float64`, 80 bytes
np7        ndarray    5x3: 15 elems, type `float64`, 120 bytes


In [13]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


In [16]:
import numpy as np
#縮寫

In [17]:
np1=np.array([1,2,3,4])
np2=np.array((5,6,7,8)) #np宣告型態 資料很大用array會有限制 用np方式建立沒有這麼多限制
print(np1)
print(np2)
print(type(np1),type(np2))
#type資料型態

[1 2 3 4]
[5 6 7 8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [20]:
np3=np.arange(0,31,2)
print (np3) 
#0~30 用2來當間隔

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [21]:
np4=np.linspace(1,15,3)

In [22]:
print (np4)

[ 1.  8. 15.]


In [23]:
np4=np.linspace(1,10,10)

In [25]:
np4

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
np5=np.zeros((5,))
print (np5)
#填5個0

[0. 0. 0. 0. 0.]


In [27]:
np6=np.ones((5,))
print (np6)

[1. 1. 1. 1. 1.]


In [30]:
np7=np.ones((5,2))
print (np7)
#都填1但是array就兩個數

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [31]:
np7=np.ones((5,3))
print (np7)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
listdata=[[1,2,3,4,5],[6,7,8,9,10]]
np8=np.array(listdata)
print(np8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [35]:
print('維度',np8.ndim)
#確認資料型態

維度 2


In [36]:
print('形狀',np8.shape)

形狀 (2, 5)


In [37]:
print('數量',np8.size)

數量 10


In [38]:
np9=np.arange(1,21)

In [39]:
np9

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
print(np9)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [41]:
np10=np9.reshape(4,5)
print(np10)
#轉換矩陣的時候數字要對!!  1~20放到4乘5的araay

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [43]:
np10a=np9.reshape(5,4)
print(np10a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [47]:
np11=np.arange(0,9)

In [48]:
print(np11)

[0 1 2 3 4 5 6 7 8]


In [49]:
print(np11[0])

0


In [50]:
print(np11[7])

7


In [51]:
print(np11[1:7])

[1 2 3 4 5 6]


In [52]:
print(np11[1:8:2])

[1 3 5 7]


In [53]:
print(np11[8:1:-1])

[8 7 6 5 4 3 2]


In [54]:
print(np11[:])

[0 1 2 3 4 5 6 7 8]


In [55]:
print(np11[:4])
#只印到4

[0 1 2 3]


In [56]:
print(np11[4:])
#從4開始印

[4 5 6 7 8]


In [57]:
np12=np.arange(1,21).reshape(5,4)
#reshape用多少值要幾*幾
#多維是立體的概念

In [58]:
np12

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [59]:
np12[0,2]
#從0開始算第三位
#[第幾排,第幾位]

3

In [60]:
np12[1,2]

7

In [61]:
np12[0,3]

4

In [63]:
print(np12[1:3,2])

[ 7 11]


In [64]:
print(np12[1:3,1:3])

[[ 6  7]
 [10 11]]


In [65]:
print(np12[::2,::2])

[[ 1  3]
 [ 9 11]
 [17 19]]


In [66]:
print(np12[:,2])

[ 3  7 11 15 19]


In [67]:
print(np12[1,:])

[5 6 7 8]


In [68]:
print(np12[:,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [70]:
np12 = np.genfromtxt('scores.csv', delimiter=',', skip_header=1)

In [71]:
np12

array([[ 1., 87., 85., 82.],
       [ 2., 92., 87., 90.],
       [ 3., 80., 91., 87.],
       [ 4., 78., 82., 95.],
       [ 5., 88., 89., 90.],
       [ 6., 82., 87., 88.],
       [ 7., 90., 92., 82.],
       [ 8., 87., 80., 90.],
       [ 9., 95., 78., 87.],
       [10., 90., 88., 95.],
       [11., 88., 89., 75.],
       [12., 82., 91., 66.],
       [13., 90., 82., 87.],
       [14., 87., 89., 92.],
       [15., 95., 87., 80.],
       [16., 90., 92., 78.],
       [17., 82., 80., 88.],
       [18., 90., 78., 93.],
       [19., 67., 87., 95.],
       [20., 91., 82., 88.],
       [21., 82., 81., 82.],
       [22., 79., 87., 90.],
       [23., 87., 92., 87.],
       [24., 92., 82., 95.],
       [25., 80., 90., 78.],
       [26., 78., 76., 91.],
       [27., 66., 90., 82.],
       [28., 89., 77., 89.],
       [29., 87., 95., 87.],
       [30., 73., 90., 92.]])

In [88]:
np9999 = np.genfromtxt('B2B發票匯入格式sample_big5.csv', delimiter=',', skip_header=1)
#作業 下載csv檔案 匯入

In [89]:
print(np9999)

[[1.e+00 7.e+00 1.e+00 2.e+00 1.e+00 1.e+03 1.e+00 1.e+03]
 [2.e+00 8.e+00 2.e+00 3.e+00 2.e+00 2.e+03 2.e+00 4.e+03]
 [3.e+00 9.e+00 3.e+00 4.e+00 1.e+00 5.e+02 1.e+00 5.e+02]
 [4.e+00 1.e+01 4.e+00 5.e+00 2.e+00 3.e+02 2.e+00 6.e+02]]


In [90]:
ls

 磁碟區 C 中的磁碟是 Windows
 磁碟區序號:  A631-A59D

 C:\Users\user\dm\TKU-DM-611630392 的目錄

2022/09/29  上午 11:57    <DIR>          .
2022/09/28  下午 11:50    <DIR>          ..
2022/09/29  上午 10:21    <DIR>          .ipynb_checkpoints
2022/09/29  上午 01:03            34,641 0922.ipynb
2022/09/29  上午 11:57            19,421 0929.ipynb
2022/09/29  上午 11:49               200 B2B發票匯入格式sample_big5.csv
2022/09/29  上午 10:25                38 hi.py
2022/09/28  下午 11:50                28 README.md
2022/09/29  上午 11:34               409 scores.csv
2022/09/28  下午 11:50             1,423 Untitled2.ipynb
2022/09/28  下午 11:50             5,459 上課內容.ipynb
               8 個檔案          61,619 位元組
               3 個目錄  920,183,119,872 位元組可用
